### ISSUE TITLE
some error running ballgown()

### ISSUE THREAD

**Issue by mthon** [alyssafrazee/ballgown#89] opened 2016-10-23 05:00 UTC
I'm following the nature protocols protocol using my own data and getting the following error while running ballgown()

> rnaseq = ballgown(dataDir = "ballgown", samplePattern = "sample-", pData=pheno_data)
> Sun Oct 23 06:49:08 2016
> Sun Oct 23 06:49:08 2016: Reading linking tables
> Sun Oct 23 06:49:10 2016: Reading intron data files
> Sun Oct 23 06:49:20 2016: Merging intron data
> Error in as.vector(x, mode) : 
>   '.SigArgs' is shorter than '.SigLength' says it should be

I have no idea wha this means.  any help would be appreciated.
here is a traceback

> traceback()
> 17: as.vector(x, mode)
> 16: as.vector(x, mode = "integer")
> 15: .local(x, ...)
> 14: as.integer(seqnames(x))
> 13: as.integer(seqnames(x))
> 12: get_out_of_bound_index(x)
> 11: valid.GenomicRanges.seqinfo(x, suggest.trim = TRUE)
> 10: valid.func(object)
> 9: validityMethod(as(object, superClass))
> 8: anyStrings(validityMethod(as(object, superClass)))
> 7: validObject(.Object)
> 6: initialize(value, ...)
> 5: initialize(value, ...)
> 4: new(Class, seqnames = seqnames, ranges = ranges, strand = strand, 
>        elementMetadata = mcols, seqinfo = seqinfo)
> 3: new_GRanges("GRanges", seqnames = seqnames, ranges = ranges, 
>        strand = strand, mcols = mcols, seqlengths = seqlengths, 
>        seqinfo = seqinfo)
> 2: GRanges(seqnames = Rle(intron$chr), ranges = IRanges(start = intron$start, 
>        end = intron$end), strand = Rle(intron$strand), id = intron$i_id, 
>        transcripts = tnamesin.ord)
> 1: ballgown(dataDir = "ballgown", samplePattern = "sample-", pData = pheno_data)

**Comment by alyssafrazee** [comment] 2016-10-24 03:53
Without knowing anything about the input data, it's hard to say what might be causing this error. Could you provide (a) the output of `sessionInfo()` and (b) a sample of what one of your `idata.ctab` files looks like? (it doesn't have to be the real numeric data, but I wonder if something's wrong with the way the file is formatted?)

**Comment by mthon** [comment] 2016-10-24 07:57
Here's a link to one of the i_data files though I don't see any problem with it:
https://dl.dropboxusercontent.com/u/320712/sample-ko1/i_data.ctab

Here's a link to all the files of one of the 9 data sets I'm working with:
https://dl.dropboxusercontent.com/u/320712/sample-ko1.zip

I should run through the tutorial and make sure that works for me.

**Comment by mthon** [comment] 2016-10-24 11:40
I got the data to load on my laptop but not on the server so I wonder if the problem is due to differences in package versions. I'll try to investigate...

**Comment by jtleek** [comment] 2016-10-25 18:31
Thanks for investigating :)

**Comment by alyssafrazee** [comment] 2016-12-31 18:56
Closing since this issue is a couple months old and the data loaded correctly on the laptop, but feel free to reopen if there is a bug we should be addressing here!

**Closed by alyssafrazee** 2016-12-31 18:56 UTC

**Comment by amizeranschi** [comment] 2017-03-09 11:25
I'm having a similar issue with the GenomicFeatures package and I am not sure what causes it. Has anyone managed to find a solution to these errors? The code that throws this error has been working for me before, so I suspect a package upgrade is causing this. However, I am not sure which package. 

Import genomic features from the file as a GRanges object ... Error in as.vector(x, mode) : 
  '.SigArgs' is shorter than '.SigLength' says it should be

**Comment by alyssafrazee** [comment] 2017-04-08 21:01
@amizeranschi the original poster solved this issue by running on a different computer, so I suspect (though can't confirm) that the problem is with package versions. 

As I asked the original poster: could you please provide the output of `sessionInfo()` and an example of what your `.ctab` files look like, in case there is a version problem or an issue with the input data?

**Comment by izzi-13** [comment] 2017-04-12 13:05
I had the same issue with GRanges (though I wasn't using ballgown) and it turned out to be due to an outdated 'Matrix' package, so if anyone's still having problems then updating that might help. :)
