### ISSUE TITLE
alternative splicing events from ballgown object

### ISSUE THREAD

**Issue by pradeepphule** [alyssafrazee/ballgown#102] opened 2017-03-29 15:19 UTC
I would like to know total no. of alternative splicing events from ballgown object or gtf file output.

i have tried to convert ballgown object into splicerlist object using SpliceR package.
splicerlist <- SpliceRList(structure(bg)$trans,structure(bg)$exon, assembly_id = "pp", source = "species", conditions = c("condition1","condition2"))
it was succesful but it gives error with spliceR functions
splicer <- spliceR(splicerlist, compareTo = "preTranscript", filters = c("expressedGenes","geneOK", "isoOK", "expressedIso", "isoClass"), useProgressBar=F )

how can i add expression values to the splicerlist? any other way to know splicing events from ballgown object?

**Comment by alyssafrazee** [comment] 2017-04-08 20:52
ballgown was designed to detect differential expression at the isoform level; unfortunately there isn't an official/supported interface between ballgown and SpliceR. (it's not clear to me what's wrong with the spliceR function; I can maybe say more if you included the error message, but given that this is ballgown and not spliceR, I'm afraid I probably won't be much help 😃 )

I'm going to close this since I don't think there are plans to work on an interface right now for spliceR, but feel free to reopen if you do find a ballgown bug we can help fix!

**Closed by alyssafrazee** 2017-04-08 20:52 UTC
