### ISSUE TITLE
Ballgown does not work for prokaryotic genomes

### ISSUE THREAD

**Issue by r2sunita** [alyssafrazee/ballgown#96] opened 2017-02-02 14:53 UTC
Hi 

I would like to use New Tuxedo Suite (HISAT, Stringtie, Ballgown) for microbial rna-seq analysis. However, Ballgown is not working for microbes primarily because microbes do not have introns. 
Wondering is there a way to fix this in Ballgown so that it can be used for differential expression analysis in prokaryotes too. It works fine for plants. 

Thanks much.
Sunita

**Comment by alyssafrazee** [comment] 2017-02-21 06:38
Hey Sunita, this is a known missing feature in ballgown (this issue is a duplicate of https://github.com/alyssafrazee/ballgown/issues/74). Sorry for the trouble! 

There isn't a timeline that I know of for adding support for this (ballgown is currently in "maintenance mode" rather than "add new functionality mode," though I think this falls somewhere in between those two things) -- but while we figure out what to do, one hack around this is to add "dummy" intron data (e.g., copy the first couple rows of the example i_data.ctab files provided with the package) so ballgown will read it in. You won't actually use the dummy data in your analysis, and some of the plotting functions might not work correctly since they assume introns, but you'll be able at least have some of the functionality.

**Closed by alyssafrazee** 2017-02-21 06:38 UTC

**Comment by wyoibc** [comment] 2019-04-13 13:30
It's been a couple of years since the last comment on this thread.  The solution of inserting a couple of lines of data from i_data.ctab (ballgown example data) does not work.  The error message does not change either.  I am going to have to give up on ballgown and use something else.
