### ISSUE TITLE
Error in smalldat[, datacols] : incorrect number of dimensions

### ISSUE THREAD

**Issue by tiramisutes** [alyssafrazee/ballgown#72] opened 2015-12-09 09:26 UTC
Hi, I　encountered a problem when I make side-by-side plots comparing mean abundances between groups, follows are my codes:
``` bash
>pData(bg) = data.frame(id=sampleNames(bg), group=rep(c("A","B","C"), each=3))
>phenotype_table = pData(bg)
> phenotype_table
   id group
1 Gh1    A
2 Gh2    A
3 Gh3    A
4 Gh4    B
5 Gh5    B
6 Gh6    B
7 Gh7    C
8 Gh8    C
9 Gh9    C
> plotMeans('XLOC_016801', bg, groupvar='group', meas='FPKM', colorby='transcript')
```
But I get this error,
``` bash
Error in smalldat[, datacols] : incorrect number of dimensions
```
can anyone tell me why? how to make it work?
And there is  3 group in my data, How can I do if I only want to compare any two of the three?
Thanks.

**Comment by filicado** [comment] 2016-01-14 15:46
I had the same issues with multiple datasets, it only happens with some XLOCs not sure what the problem is

**Comment by raymond301** [comment] 2016-01-21 16:43
The documentation says use 0/1 to define groups, which I do:
> pData(bg)
         id group
1 s_10B-180     0
2 s_10C-180     0
3 s_14B-180     0
4 s_14C-180     0
5 s_28A-180     1
6 s_28B-180     1
7 s_34A-180     1
8 s_34B-180     1

I get the same error as well.

**Comment by filicado** [comment] 2016-01-25 12:21
I think this happens with genes that only have 1 transcript. I'm not a code wizard but:

      t_id = texpr(gown, 'all')$t_id
            smalldat = texpr(gown, meas)[t_id %in% gtrans$tid,]
            datacols = which(sampleNames(gown) %in% samples[[p]])
            tmeans = rowMeans(smalldat[,datacols])

rowMeans(smalldat[,datacols]) seems to fail when there is only one transcript. If use

 if (is.null(dim(smalldat)))
      {
      tmeans = mean(smalldat[datacols])
      }
      else
      {
      tmeans = rowMeans(smalldat[,datacols])
      }

it works. However this needs further fixing for correct colour assignment etc.

**Comment by jtleek** [comment] 2016-01-25 18:29
Thanks for letting us know we'll try to get this fix done as soon as
possible.

**Comment by yushuen** [comment] 2016-02-23 19:06
As what you already done for "fix gexpr for 1-sample bg objects", just pass "drop=F":
 
       if (colorby == "transcript") {
            t_id = texpr(gown, "all")$t_id
            smalldat = texpr(gown, meas)[t_id %in% gtrans$tid, , drop=F]
            datacols = which(sampleNames(gown) %in% samples[[p]])
            tmeans = rowMeans(smalldat[, datacols, drop=F])
       }

       if (colorby == "exon") {
           e_id = eexpr(gown, "all")$e_id
           smalldat = eexpr(gown, meas)[e_id %in% gtrans$id, , drop=F]
           datacols = which(sampleNames(gown) %in% samples[[p]])
           emeans = rowMeans(smalldat[, datacols, drop=F])
       }


It works in my case.

**Comment by orchid00** [comment] 2016-09-02 05:19
Hi @jtleek  I'm using the latest version to date ballgown_2.4.2
I got a very similar error to this thread Error in smalldat[, colIndex] : incorrect number of dimensions. 
when using plotTranscript.

It seems this hasn't been fixed yet.... 

Also, another question, is there any format requirements for the files. 
I have the same files as the example : t_data.ctab, i_data.ctab, i2t.ctab, e_data.ctab, e2t.ctab
after some errors and looking closely to the example files I noticed that my second column names are chr1, chr2 etc... and the example has only numbers e.g 1,2,etc 
So, now that I fixed the "chr" the other question is about Un for unplaced would that be even recognised? or is it better to remove it from the input data? 
it seems there is no problem with chromosomes X and Y or at least nothing by now.

**Comment by filicado** [comment] 2016-09-09 13:59
I wouldn't count for a fix soon, the package doesn't seem to be actively developed any more.
But you can apply the fix suggested by yushuen that does the trick.

**Comment by alyssafrazee** [comment] 2016-09-09 14:51
Sorry! The package is maintained (though not actively developed), but turnaround time gets long since the maintainers all work full time on projects that aren't this one. I'll take a look as soon as I can (likely in the next few weeks).

**Comment by alyssafrazee** [comment] 2016-09-20 04:26
OK, this should be fixed as of this commit: https://github.com/alyssafrazee/ballgown/pull/85/commits/20f3c858aff808b5601f7d03748d29405e2a47a1

I'm leaving to @JMF47 to get this pushed appropriately to BioC devel, but for now, pulling down the "devel" branch of this repository should work. Jack, repeating myself from the PR, let me know if there's something I can do to help get the branch pushed to BioC correctly.

**Closed** 2016-09-20 17:04 UTC

**Comment by filicado** [comment] 2016-11-03 15:45
Great, thanks for fixing!
